# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      run: powershell -Command "Invoke-WebRequest -Uri https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1"
    - name: Install .NET SDK
      run: |
        powershell -ExecutionPolicy Bypass -File .\dotnet-install.ps1 -Channel 7.0 -Architecture x64
        $dotnetPath = [System.IO.Path]::Combine($env:USERPROFILE, '.dotnet')
        echo "DOTNET_ROOT=$dotnetPath" >> $env:GITHUB_ENV
        echo "$dotnetPath" >> $env:PATH

    - name: Verify .NET SDK Version
      run: dotnet --version

