# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      run: powershell -Command "Invoke-WebRequest -Uri https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1"
    - name: Setup .NET 2
      run: powershell -ExecutionPolicy Bypass -File .\dotnet-install.ps1 -Channel 7.0 -Architecture x64 
    - name: Setup .NET 3
      run: dotnet --version
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      working-directory: Analytics-Puller-Service\data-agent-service
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Analytics-Puller-Service\data-agent-service

