name: .NET
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      run: powershell -Command "Invoke-WebRequest -Uri https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1"

    - name: Install .NET SDK if not already installed
      run: |
        $dotnetVersion = "7.0.410"
        if (-not (dotnet --list-sdks | Select-String $dotnetVersion)) {
          powershell -ExecutionPolicy Bypass -File .\dotnet-install.ps1 -Channel 7.0 -Architecture x64
          $dotnetPath = [System.IO.Path]::Combine($env:USERPROFILE, '.dotnet')
          echo "DOTNET_ROOT=$dotnetPath" >> $env:GITHUB_ENV
          echo "$dotnetPath" >> $env:PATH
        } else {
          Write-Host ".NET SDK $dotnetVersion is already installed."
        }

    - name: Verify .NET SDK Version
      run: dotnet --version
