# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Set environment variable for app directory
      run: echo "APP_DIR=Pass-List-App/app" >> $GITHUB_ENV
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --package-lock-only
      working-directory: ${{ env.APP_DIR }}
    - run: npm ci
      working-directory: ${{ env.APP_DIR }}
    - run: npm run build --if-present
      working-directory: ${{ env.APP_DIR }}
    - run: sudo yarn test --coverage --coverageDirectory='covertura_pruebas'
      working-directory: ${{ env.APP_DIR }}

    - name: Upload resource count artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage_Results
        path: Pass-List-App/app/covertura_pruebas
